# Generated by Django 5.2 on 2025-06-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='photo',
        ),
        migrations.AddField(
            model_name='dish',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts_app.post'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='cooking_method',
            field=models.CharField(choices=[('Prodziż', 'Pieczone'), ('Smażone', 'Gotowane'), ('Parzone', 'Surowe')], default='', max_length=30),
        ),
    ]
